import random

questions = [
    "Solve log_3(x) = 2 and explain what this means using the idea of 'how many times 3 multiplies itself'.",
    "Explain what a homomorphism is by showing how addition mod 5 maps into addition mod 10.",
    "Explain group theory by using the symmetries of a square (rotations and flips) as an example.",
    "If a box has 3 red and 5 blue balls and you draw **without replacement**, what is the probability the first ball is red? Explain the reasoning step by step.",
    "Explain the Fourier transform by showing how the sound of a tuning fork can be broken into frequencies.",
    "Explain the Laplace transform by demonstrating how it simplifies solving y' + 3y = 2.",
    "Visualize y = x^2 + 3x by locating its vertex, intercepts, and showing how the parabola shifts from y = x^2.",
    "Solve 2x + 5 = 11 and explain it as 'undoing operations' for a 7th-grade student.",
    "Find the derivative of x^3 and explain using the idea of the 'instantaneous speed' of x^3 growing.",
    "Explain what an integral is by describing the area under the curve of y = 2x between x = 0 and x = 3.",
    "Explain what a vector space is using the example of all 2D arrows drawn on graph paper.",
    "Explain what a basis is by showing that the vectors (1,0) and (0,1) can describe any point on a grid.",
    "Explain eigenvalues and eigenvectors using the example of stretching a rubber band only in one direction.",
    "Compute the determinant of a 2×2 matrix and explain how it tells you how area is scaled.",
    "Explain what a matrix is by relating it to transformations like rotating a point on the plane.",
    "Find the inverse of a simple 2×2 matrix and explain why it 'undoes' the transformation.",
    "Explain what a limit is by describing why (x^2 − 1)/(x − 1) approaches 2 as x → 1 even though x = 1 causes a hole.",
    "Compute lim(x→0) sin(x)/x and explain using the unit circle argument.",
    "Explain the chain rule by differentiating (3x^2 + 1)^5 and showing the inner and outer functions.",
    "Explain the product rule by differentiating x^2·sin(x) and describing why 'each part takes turns being differentiated'.",
    "Explain the quotient rule by differentiating (2x+1)/(x^2+3).",
    "Explain partial derivatives using the example of temperature T(x,y) on a metal plate.",
    "Explain the gradient by showing how it points toward the steepest increase on a hill map.",
    "Explain divergence and curl using a diagram of water flow in a river.",
    "Explain the Taylor series by expanding sin(x) around x = 0 and showing the first 3 terms.",
    "Explain the binomial theorem using (a + b)^4 and show the combinatorial coefficients.",
    "Explain the difference between permutation and combination using the example of selecting class leaders from 4 students.",
    "Explain what a probability distribution is using the example of rolling a loaded die.",
    "Explain what a random variable is using the number of heads in 3 coin flips.",
    "Explain the normal distribution using students' test scores as an example.",
    "Compute the expected value of rolling a 6-sided die and explain why it's not necessarily a value the die can show.",
    "Explain variance and standard deviation using 3 test scores: 70, 70, 100.",
    "Explain conditional probability with the example 'probability of drawing a king given that the card is a face card'.",
    "Explain Bayes' theorem with a simple medical test false-positive/false-negative example.",
    "Explain what a function is using a vending machine analogy.",
    "Explain injective, surjective, and bijective functions using arrow diagrams between sets.",
    "Explain what a polynomial is and show examples of degree 0, 1, 2, and 3.",
    "Explain what a root of a polynomial is using x^2−9 and show why ±3 are solutions.",
    "Solve x^2 − 5x + 6 = 0 and explain why factoring works.",
    "Explain the quadratic formula and derive it from completing the square.",
    "Explain an arithmetic sequence using the pattern: 4, 9, 14, 19, …",
    "Explain a geometric sequence using money doubling every day.",
    "Explain what a series is by summing the first 5 terms of 2 + 5 + 8 + 11 + …",
    "Explain convergence using the infinite series 1/2 + 1/4 + 1/8 + …",
    "Explain an infinite geometric series using the idea of repeatedly folding a paper strip.",
    "Explain what a complex number is using the coordinate plane.",
    "Explain the imaginary unit i using the idea that it is the square root of −1 and show why i^2 = −1.",
    "Convert 3 + 4i to polar form and explain the meaning of magnitude and angle.",
    "Explain Euler's formula e^{ix} = cos(x) + i sin(x) using a unit circle rotation example.",
    "Explain what a differential equation is using the example y' = 3y.",
    "Explain first-order linear differential equations using y' + y = e^x.",
    "Explain what a separable differential equation is using dy/dx = xy.",
    "Explain what a boundary value problem is using temperature at both ends of a metal rod.",
    "Explain what a linear transformation is by showing how a matrix rotates points.",
    "Explain the kernel of a linear transformation using a matrix that squashes all points onto a line.",
    "Explain the image of a linear transformation using T(x,y) = (x,0).",
    "Explain what an isomorphism is by showing that R^2 and the set of complex numbers behave the same algebraically.",
    "Explain what a metric space is using the idea of different distance formulas (Manhattan vs Euclidean).",
    "Explain continuity using a graph with no jumps or holes.",
    "Explain uniform continuity using f(x) = x^2 over the interval [0,1].",
    "Explain what a topology is using the example of open intervals on the real line.",
    "Explain what a compact set is using closed intervals like [a, b].",
    "Explain open and closed sets using the real line and simple intervals.",
    "Explain what a prime number is using factor trees.",
    "Explain the Fundamental Theorem of Arithmetic with the example 180 = 2^2·3^2·5.",
    "Explain modular arithmetic using a 12-hour clock.",
    "Explain congruences with the example 17 ≡ 5 (mod 12).",
    "Explain the gcd using gcd(36, 15).",
    "Explain the Euclidean algorithm using the steps for gcd(84, 30).",
    "Explain what a ring is using integers mod 6.",
    "Explain what a field is using rational numbers as an example.",
    "Explain what an ideal is using the multiples of 4 inside the integers.",
    "Explain quotient rings using Z/5Z as an example.",
    "Explain what a subgroup is using the even integers inside all integers.",
    "Explain Lagrange's theorem using subgroups of the group of cube rotations.",
    "Explain what a cyclic group is using the group generated by rotating a triangle.",
    "Explain S_n using the permutations of 3 students’ seating order.",
    "Explain what a normal subgroup is using integers inside rational numbers.",
    "Explain quotient groups using Z/2Z as flipping orientation.",
    "Explain what a group isomorphism is using (Z_6, +) and Z_2 × Z_3.",
    "Explain what a graph is using a map of cities connected by roads.",
    "Explain what a tree is using family tree structure.",
    "Explain what a connected graph is using subway stations and tunnels.",
    "Explain paths and cycles using walking routes around school buildings.",
    "Explain Eulerian vs Hamiltonian paths using examples of visiting hallways vs visiting rooms once.",
    "Explain what a spanning tree is using a network of computers.",
    "Explain adjacency matrices using a 4-node graph example.",
    "Explain what a probability density function is using a triangular distribution.",
    "Explain a cumulative distribution function using heights of students.",
    "Explain the law of large numbers using repeated coin flips.",
    "Explain the central limit theorem using the average of many small measurement errors.",
    "Explain what a Markov chain is using weather transitions (sunny→rainy→sunny…).",
    "Explain a transition matrix using a 3-state Markov chain of mood changes.",
    "Explain entropy using a probability distribution over letters in English.",
    "Explain mutual information using the relation between weather and umbrella usage.",
    "Explain convolution using blurring an image with a 3×3 filter.",
    "Explain convolution for signals using how echo mixes with the original audio.",
    "Explain the Z-transform using a discrete signal like 1, 2, 4, 8, …",
    "Explain the difference between Fourier series and Fourier transform using periodic vs non-periodic signals.",
    "Explain partial fraction decomposition using 1/(x^2 − 1).",
    "Explain orthogonality using dot products of (1,0) and (0,1).",
    "Explain what an inner product space is using the geometry of angles.",
    "Explain Gram–Schmidt by orthogonalizing (1,1) and (1,0).",
    "Explain projecting a vector onto a subspace using projection onto the x-axis.",
    "Explain what an eigenbasis is using diagonalizing a scaling matrix.",
    "Explain diagonalization using a matrix that stretches x but flips y."
]
random_question = random.choice(questions)
